project:
  type: website
  output-dir: docs

website:
  title: "EcoSense Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: Research.qmd
        text: Research
      - href: Teaching.qmd
        text: Teaching
      - href: Publications.qmd
        text: Publications
      - href: Opportunities.qmd
        text: Opportunities

format:
  html:
    theme: cosmo
    css: styles.css
    toc: False
    page-layout: full
    
    



